@startuml Container
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(administrador, "Administrador", "Os administradores gerenciam o sistema")
Person(cliente, "Cliente", "O cliente solicita corridas no aplicativo")
Person(prestador, "Prestador de serviço", "O prestador atende os serviços solicitados pelo aplicativo")

System_Ext(banco, "Banco", "Permite que o pagamento das corridas seja feito")
System_Ext(maps, "Google Maps", "Fornece a localização necessária para os serviços prestados")

System_Boundary(sistema, "TranSender") {
    Container(spa, "Single Page Application", "Javascript com React", "Fornece todas as funcionalidades do TranSender aos administradores por meio de seu navegador.")
    Container(ma, "Mobile App", "Javascript com React-Native", "Fornece funcionalidades do TranSender aos clientes e prestadores através de um dispositivo móvel.")
    Container(db, "Database", "Banco de dados relacional", "Armazena informações de usuários, corridas, credenciais, etc.")
    Container(api, "API Application", "Java com Spring MVC", "Fornece funcionalidades ao TranSender por meio de uma API JSON/HTTP.")

    Rel(api, maps, "Tem comunicação", "JSON/HTTPS")
    Rel(api, banco, "Tem comunicação", "JSON/HTTPS")
    Rel(api, db, "Leitura e escrita", "JDBC")

    Rel(spa, api, "Usa", "JSON/HTTPS")
    Rel(ma, api, "Usa", "JSON/HTTPS")
}

Rel(cliente, ma, "Usa")
Rel(prestador, ma, "Usa")
Rel(administrador, spa, "Usa", "HTTPS")

@enduml
